export const FETCH_BASKET_DATA_START = 'FETCH_BASKET_DATA_START';
export const FETCH_BASKET_DATA_SUCCESS = 'FETCH_BASKET_DATA_SUCCESS';
export const FETCH_BASKET_DATA_FAILURE = 'FETCH_BASKET_DATA_FAILURE';
